### ISSUE TITLE
[Help] Auto Mute for Linux 

### ISSUE THREAD

**Issue by DSDV** [CubE135/AutoMute#1]
Hi there (: 
i and nearly all of my friends used your plugin and its predecessor for years now (i guess nearly 10?).
Since most of us switched to Linux we miss it dearly. 
Is there a chance you might add a Linux version or can help us to create one?
Ofc i can collect a little for a paypaled cup of coffee <3

with kind regards

**Comment by CubE135** [comment]
Hi, and thanks for using my Plugin :)
I'll look into what it takes to get this running on linux.
I'll keep you updated here :)

**Comment by DSDV** [comment]
That is great news :D
I'm really happy to hear that

**Comment by CubE135** [comment]
Hi, sadly i was not able to get it working on linux.
As this plugin is open source, maybe a more advanced Plugin developer can get this done.
I myself am not skilled enough in TeamSpeak Plugin Development to make  this happen.
Sorry :(

**Comment by DSDV** [comment]
sad to read :( 
but thanks for trying <3

**Comment by DSDV** [comment]
Found a Linux version here https://github.com/ReneHollander/automute
so there is a plugin for both platforms <3
