### ISSUE TITLE
Plugin fails to load after latest TeamSpeak 3 update

### ISSUE THREAD

**Issue by jagardaniel** [CubE135/AutoMute#2]
Hello!

TeamSpeak released a new version a couple of days ago where they increased the minimum API version to 26. After this change Auto Mute fails to load because the API version is not compatible (23).

From their [changelog](https://community.teamspeak.com/t/teamspeak-3-client-3-6-0/41112):
```
=== Client Release 3.6.0 - 14 Jun 2023
! Plugin API increased to 26 as workaround for Qt update incompatibility
```

I post this issue more as information and not "you have to fix!!".

Thanks for a great plugin, I have been using it for a few years now :)

/Daniel

**Comment by CubE135** [comment]
Hey, thanks for using my Plugin :)
I just updated my TeamSpeak client and i can confirm this.
I'll have a look at the Problem this weekend :)
Will update you on the Progress.

**Comment by CubE135** [comment]
@jagardaniel Just updated the Plugin. Waiting on TeamSpeak to accept the updated version :)

**Comment by jagardaniel** [comment]
Awesome, thanks for the help! I will give it a try when the updated version is available :)

**Comment by yfunk** [comment]
@CubE135 Apparently TeamSpeak [isn't accepting and reviewing any add-ons](https://community.teamspeak.com/t/update-or-submit-of-the-addons-on-myteamspeak/9569/15) anymore. So the best option is probably to create a new release on GitHub and host the download here (and maybe post about it on the forums?).

**Comment by CubE135** [comment]
Wow, that is poor from TeamSpeak. Anyway, great idea. Just added the new release including a download to the ts3_plugin file: https://github.com/CubE135/AutoMute/releases/tag/v1.1.8
